/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

/**
 *
 * @author montedori.riccardo
 */
import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;

public class InterfacciaAtleta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfacciaAtleta.class.getName());

    /**
     * Creates new form InterfacciaAtleta
     */
    
    private CorsiaAtleta[] corsie = new CorsiaAtleta[4];
    private Color[] coloriAtleti = {Color.RED, Color.YELLOW, Color.GREEN, Color.CYAN};
    
   public InterfacciaAtleta() {
        super("Relay Runners");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 500);
        setLayout(new BorderLayout(5, 5));

        
        JPanel pnlCentrale = new JPanel(new GridLayout(4, 1, 0, 5));
        pnlCentrale.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        for (int i = 0; i < 4; i++) {
            corsie[i] = new CorsiaAtleta("Runner " + (i + 1), coloriAtleti[i]);
            pnlCentrale.add(corsie[i]);
        }

        
        JPanel pnlSud = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 10));
        
        JComboBox<String> comboVelocita = new JComboBox<>(new String[]{"Lento", "Medio", "Veloce"});
        JButton btnAvvia = new JButton("Avvia");
        JButton btnSospende = new JButton("Sospende");
        JButton btnRiprende = new JButton("Riprende");
        JButton btnFerma = new JButton("Ferma");

        
        btnSospende.setEnabled(false);
        btnRiprende.setEnabled(false);
        btnFerma.setEnabled(false);

        pnlSud.add(comboVelocita);
        pnlSud.add(btnAvvia);
        pnlSud.add(btnSospende);
        pnlSud.add(btnRiprende);
        pnlSud.add(btnFerma);

        add(pnlCentrale, BorderLayout.CENTER);
        add(pnlSud, BorderLayout.SOUTH);
    }
   
   private class CorsiaAtleta extends JPanel {
        private JPanel areaCorsa;
        private JLabel lblStato;
        private int posizioneX = 10;
        private Color colorePunto;

        public CorsiaAtleta(String nome, Color colore) {
            this.colorePunto = colore;
            setLayout(new BorderLayout());
            setBorder(new LineBorder(Color.DARK_GRAY, 1));

           
            areaCorsa = new JPanel() {
                @Override
                protected void paintComponent(Graphics g) {
                    super.paintComponent(g);
                    Graphics2D g2 = (Graphics2D) g;
                    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                    g2.setColor(colorePunto);
                
                    g2.fillOval(posizioneX, getHeight() / 2 - 10, 20, 20);
                }
            };
            areaCorsa.setBackground(new Color(235, 235, 235));

         
            JPanel pnlInfo = new JPanel(new GridLayout(1, 2));
            pnlInfo.setPreferredSize(new Dimension(200, 0));
            pnlInfo.setBackground(new Color(215, 225, 245));
            pnlInfo.setBorder(BorderFactory.createMatteBorder(0, 1, 0, 0, Color.GRAY));

            JLabel lblNome = new JLabel(nome);
            lblNome.setFont(new Font("SansSerif", Font.PLAIN, 14));
            lblNome.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 0));

            lblStato = new JLabel("0", SwingConstants.RIGHT);
            lblStato.setFont(new Font("SansSerif", Font.BOLD, 16));
            lblStato.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 15));

            pnlInfo.add(lblNome);
            pnlInfo.add(lblStato);

            add(areaCorsa, BorderLayout.CENTER);
            add(pnlInfo, BorderLayout.EAST);
        }

       
        public void aggiornaPosizione(int x, String stato) {
            this.posizioneX = x;
            this.lblStato.setText(stato);
            repaint(); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfacciaAtleta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
